In [1]:
import numpy as np

In [2]:
numeros = [1,2,3,4]

In [3]:
array = np.array(numeros)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
array = np.random.randint(0,100,10)

In [11]:
array

array([92, 78, 87, 49, 98, 93, 84, 25, 66, 25])

In [12]:
array.max()

98

In [13]:
filtro = array > 30
array2 = array[filtro]

In [14]:
array2

array([92, 78, 87, 49, 98, 93, 84, 66])