In [1]:
import tensorflow as tf
import numpy as np

In [8]:
aleatorio_a = np.random.uniform(0,50,(4,4))

In [9]:
aleatorio_a

array([[43.94576506,  9.35272975, 25.3841492 ,  4.4963801 ],
       [ 3.78220297, 10.76072602, 28.31460526, 39.49254194],
       [16.38584745, 32.54175437, 16.50632647, 14.84492632],
       [21.96400603, 22.79808099, 46.008944  , 37.91240205]])

In [10]:
aleatorio_b = np.random.uniform(0,50,(4,1))

In [12]:
aleatorio_b

array([[17.06464928],
       [ 0.29493037],
       [35.91627867],
       [14.57637296]])

In [15]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [17]:
suma = a + b
multiplicacion = a * b

In [20]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_suma)

[[61.010414 26.41738  42.4488   21.56103 ]
 [ 4.077133 11.055656 28.609535 39.78747 ]
 [52.302124 68.45804  52.422607 50.761204]
 [36.54038  37.374454 60.58532  52.488777]]


In [21]:
with tf.Session() as sesion:
    resultado_multiplicacion = sesion.run(suma,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_multiplicacion)

[[61.010414 26.41738  42.4488   21.56103 ]
 [ 4.077133 11.055656 28.609535 39.78747 ]
 [52.302124 68.45804  52.422607 50.761204]
 [36.54038  37.374454 60.58532  52.488777]]


In [24]:
caracteristicas = 10
neuronas = 4

In [25]:
x = tf.placeholder(tf.float32,(None, caracteristicas))

In [29]:
w = tf.Variable(tf.random_normal([caracteristicas, neuronas]))

In [30]:
b = tf.Variable(tf.ones([neuronas]))

In [31]:
multiplicacion = tf.matmul(x,w)

In [32]:
z = tf.add(multiplicacion,b)

In [33]:
activacion = tf.sigmoid(z)

In [34]:
inicializacion = tf.global_variables_initializer()

In [35]:
valores_x = np.random.random([1,caracteristicas])

In [36]:
valores_x

array([[0.88357897, 0.62954232, 0.56831121, 0.2853879 , 0.47223578,
        0.27566017, 0.22901157, 0.33182313, 0.74637515, 0.45467952]])

In [37]:
with tf.Session() as sesion:
    sesion.run(inicializacion)
    resultado = sesion.run(activacion, feed_dict={x:valores_x})

In [39]:
print(resultado)

[[0.8137641  0.36562943 0.8939692  0.92549324]]
