In [5]:
import tensorflow as tf

In [6]:
mensaje1 = tf.constant("Hola ")
mensaje2 = tf.constant("mundo")

In [7]:
with tf.Session() as sesion:
    resultado = sesion.run(mensaje1 + mensaje2)

In [10]:
resultado

b'Holamundo'

In [11]:
a = tf.constant(10)
b = tf.constant(5)

In [12]:
with tf.Session() as sesion:
    resultado = sesion.run(a + b)

In [13]:
resultado

15

In [14]:
constante = tf.constant(15)

In [15]:
matriz1 = tf.fill((6,6),10)

In [16]:
matriz2 = tf.random_normal((5,5))

In [17]:
matriz3 = tf.random_uniform((4,4), minval=0, maxval=5)

In [18]:
matriz_ceros = tf.zeros((2,2))

In [19]:
matriz_unos = tf.ones((3,3))

In [20]:
operaciones = [constante, matriz1, matriz2, matriz3, matriz_ceros, matriz_unos]

In [21]:
with tf.Session() as sesion:
    for op in operaciones:
        print(sesion.run(op))
        print("\n")

15


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


[[ 0.05603584  0.9885294   0.1363545  -1.0966351   1.5248381 ]
 [-1.2134427   0.01101645 -0.6306134   0.5648248   0.4550332 ]
 [ 0.2571779   0.58485085  0.66088325 -0.10074911  0.2699559 ]
 [-1.0154351   0.83979434  0.60791296  2.3062563   0.61649823]
 [ 0.41935724 -0.4649703   0.6929278   0.49351627  0.08450711]]


[[0.06992459 4.036713   2.8776848  3.965773  ]
 [2.8412943  3.0232115  4.483807   2.9547315 ]
 [1.1250222  1.4355046  4.533891   3.5979695 ]
 [3.975926   3.1173878  3.1243289  4.119125  ]]


[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


