In [1]:
import tensorflow as tf

In [2]:
tensor = tf.random_uniform((5,5),0,1)

In [3]:
variable = tf.Variable(initial_value = tensor)

In [4]:
print(variable)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>


In [5]:
inicializador = tf.global_variables_initializer()

In [8]:
with tf.Session() as sesion:
    sesion.run(inicializador)
    print(sesion.run(variable))

[[0.89128256 0.3458612  0.99798834 0.45084524 0.00134206]
 [0.36125958 0.6307787  0.990031   0.46992576 0.9916574 ]
 [0.71180415 0.11349022 0.39826775 0.19032598 0.03253543]
 [0.95839775 0.8254175  0.45623648 0.47896564 0.7276063 ]
 [0.8021897  0.35865057 0.2283827  0.7293397  0.11711705]]


In [7]:
print(resultado)

[[0.781016   0.51130116 0.03420913 0.31184602 0.5556102 ]
 [0.6058203  0.48951745 0.5196012  0.996344   0.5739353 ]
 [0.41134286 0.0104084  0.28565812 0.48002446 0.18662715]
 [0.8076484  0.37232292 0.36250913 0.74854124 0.23912501]
 [0.72147334 0.03899837 0.48545527 0.32537508 0.64358795]]


In [9]:
incognitas = tf.placeholder(tf.float32, shape=(20,20))

In [10]:
print(incognitas)

Tensor("Placeholder:0", shape=(20, 20), dtype=float32)
